version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    networks:
      - studying_network
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development

networks:
  studying_network:
    external: true
